services:
  entrypoint_caddy:
    image: caddy:2
    container_name: caddy-entrypoint
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - proxy
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8443:80"
    environment:
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "VERY_LONG_RANDOM_STRING"
      INVITATIONS_ALLOWED: "true"
    networks:
      - proxy

networks:
  proxy:
    external: true